name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add VM to known hosts
      run: |
        ssh-keyscan -H 172.167.215.69 >> ~/.ssh/known_hosts

    - name: Deploy files to Azure VM
      run: |
       rsync -avz --delete \
          --exclude '.git/' \
          --exclude 'deploy-to-azure.sh' \
          --exclude '.github/' \
          ./ azureuser@172.167.215.69:/var/www/html/
